using Spendly.Application.Interfaces;

namespace Spendly.Application.UseCases.Exports
{
    /// <summary>
    /// Generates a simple PDF monthly report as a formatted text file.
    /// For a production app, QuestPDF or similar would be used,
    /// but this avoids adding a heavy NuGet dependency.
    /// Instead, we generate a clean HTML report that can be printed as PDF from the browser.
    /// </summary>
    public class ExportMonthlyReportUseCase
    {
        private readonly IExpenseRepository _expenseRepo;
        private readonly IIncomeRepository _incomeRepo;

        public ExportMonthlyReportUseCase(IExpenseRepository expenseRepo, IIncomeRepository incomeRepo)
        {
            _expenseRepo = expenseRepo;
            _incomeRepo = incomeRepo;
        }

        public async Task<string> ExecuteAsync(int userId, int year, int month)
        {
            var startDate = new DateTime(year, month, 1);
            var endDate = startDate.AddMonths(1).AddDays(-1);

            var expenses = (await _expenseRepo.GetByDateRangeAsync(userId, startDate, endDate)).ToList();
            var totalExpenses = expenses.Sum(e => e.Amount.Value);
            var totalIncome = await _incomeRepo.GetTotalAmountAsync(userId, startDate, endDate);
            var balance = totalIncome - totalExpenses;

            var categoryBreakdown = expenses
                .GroupBy(e => e.Category)
                .Select(g => new { Category = g.Key, Total = g.Sum(e => e.Amount.Value), Count = g.Count() })
                .OrderByDescending(c => c.Total)
                .ToList();

            var topExpenses = expenses
                .OrderByDescending(e => e.Amount.Value)
                .Take(10)
                .ToList();

            var monthName = startDate.ToString("MMMM yyyy");

            var html = $@"
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Spendly Report - {monthName}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #333; }}
        h1 {{ color: #0d6efd; border-bottom: 3px solid #0d6efd; padding-bottom: 10px; }}
        h2 {{ color: #495057; margin-top: 30px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th {{ background: #f8f9fa; text-align: left; padding: 12px; border-bottom: 2px solid #dee2e6; }}
        td {{ padding: 10px 12px; border-bottom: 1px solid #eee; }}
        .summary-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 20px 0; }}
        .summary-card {{ background: #f8f9fa; border-radius: 12px; padding: 20px; text-align: center; }}
        .summary-card .value {{ font-size: 28px; font-weight: bold; margin: 5px 0; }}
        .summary-card .label {{ font-size: 12px; text-transform: uppercase; color: #6c757d; letter-spacing: 1px; }}
        .text-success {{ color: #198754; }}
        .text-danger {{ color: #dc3545; }}
        .text-primary {{ color: #0d6efd; }}
        .footer {{ margin-top: 40px; text-align: center; color: #adb5bd; font-size: 12px; border-top: 1px solid #dee2e6; padding-top: 15px; }}
        @@media print {{ body {{ padding: 0; }} }}
    </style>
</head>
<body>
    <h1>📊 Monthly Report — {monthName}</h1>

    <div class='summary-grid'>
        <div class='summary-card'>
            <div class='label'>Total Income</div>
            <div class='value text-success'>${totalIncome:N2}</div>
        </div>
        <div class='summary-card'>
            <div class='label'>Total Expenses</div>
            <div class='value text-danger'>${totalExpenses:N2}</div>
        </div>
        <div class='summary-card'>
            <div class='label'>Balance</div>
            <div class='value {(balance >= 0 ? "text-success" : "text-danger")}'>${balance:N2}</div>
        </div>
    </div>

    <h2>📂 By Category</h2>
    <table>
        <thead><tr><th>Category</th><th>Amount</th><th>Count</th><th>% of Total</th></tr></thead>
        <tbody>";

            foreach (var cat in categoryBreakdown)
            {
                var pct = totalExpenses > 0 ? (cat.Total / totalExpenses * 100) : 0;
                html += $"<tr><td>{cat.Category}</td><td>${cat.Total:N2}</td><td>{cat.Count}</td><td>{pct:N1}%</td></tr>";
            }

            html += @"
        </tbody>
    </table>

    <h2>🔝 Top 10 Expenses</h2>
    <table>
        <thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th></tr></thead>
        <tbody>";

            foreach (var exp in topExpenses)
            {
                html += $"<tr><td>{exp.Date:MMM dd}</td><td>{exp.Description}</td><td>{exp.Category}</td><td>${exp.Amount.Value:N2}</td></tr>";
            }

            html += $@"
        </tbody>
    </table>

    <div class='footer'>
        Generated by Spendly on {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC
    </div>
</body>
</html>";

            return html;
        }
    }
}
