using Spendly.Domain.Exceptions;

namespace Spendly.Domain.Entities
{
    public class Expense
    {
        // Id is generated by the database (Code First)
        public int Id { get; private set; }
        public decimal Amount { get; private set; }
        public string Description { get; private set; }
        public DateTime Date { get; private set; }
        public string Category { get; private set; }

        protected Expense() { } 

        public Expense(decimal amount, string description, DateTime date, string category)
        {
            Validate(amount, description, date, category);

            Amount = amount;
            Description = description;
            Date = date;
            Category = category;
        }

        public void Update(decimal amount, string description, DateTime date, string category)
        {
            Validate(amount, description, date, category);

            Amount = amount;
            Description = description;
            Date = date;
            Category = category;
        }

        private void Validate(decimal amount, string description, DateTime date, string category)
        {
            if (amount <= 0)
                throw new InvalidDomainException("Amount must be greater than zero.");

            if (string.IsNullOrWhiteSpace(description))
                throw new InvalidDomainException("Description cannot be empty.");

            if (string.IsNullOrWhiteSpace(category))
                throw new InvalidDomainException("Category cannot be empty.");

            if (date > DateTime.UtcNow)
                throw new InvalidDomainException("Date cannot be in the future.");
        }
    }
    
}
