using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Spendly.Domain.Entities
{
    public class Expense
    {
        // Id is generated by the database (Code First)
        public int Id { get; private set; }
        public decimal Amount { get; private set; }
        public string Description { get; private set; }
        public DateTime Date { get; private set; }
        public string Category { get; private set; }

        protected Expense() { } 

        public Expense(decimal amount, string description, DateTime date, string category)
        {
            // A payment must always have a positive amount
            if (amount <= 0)
            {
                throw new ArgumentException("Amount must be greater than zero.", nameof(amount));
            }

            if (string.IsNullOrWhiteSpace(description))
            {
                throw new ArgumentException("Description cannot be empty.", nameof(description));
            }

            if (string.IsNullOrWhiteSpace(category))
            {
                throw new ArgumentException("Category cannot be empty.", nameof(category));
            }

            Amount = amount;
            Description = description;
            Date = date;
            Category = category;
        }

        public void Update(decimal amount, string description, DateTime date, string category)
        {
            if (amount <= 0)
                throw new ArgumentException("Amount must be greater than zero");

            Amount = amount;
            Description = description;
            Date = date;
            Category = category;
        }
    }
}
